Replace `xsalsa20poly1305` with `crypto_secretbox`
serenity-rs/songbird pull request #198
Opened 2023-07-29 16:47 UTC by Sebbl0508

`xsalsa20poly1305` is listed as deprecated

2023-07-29 23:30 UTC, FelixMcFelix requested changes
Thanks, I wasn't aware that the library had been deprecated. There are some minor changes I'd like to ask for, otherwise I can see it's mostly a drop-in replacement.

2023-07-29 23:30 UTC, FelixMcFelix commented on Cargo.toml
> +version = "0.3.3"
Please don't change this: we'll handle this separately when we make a release at some later time.

2023-07-29 23:30 UTC, FelixMcFelix commented on Cargo.toml
> +[dependencies.crypto_secretbox]
Can you move the `[dependencies.crypto_secretbox]` block to its correct alphabetical place? I.e., between byteorder and dashmap.

2023-07-29 23:30 UTC, FelixMcFelix commented on Cargo.toml
> +    "crypto_secretbox",
Ditto on alphabetical order.

2023-07-29 23:30 UTC, FelixMcFelix commented on src/driver/crypto.rs
> +    pub const NONCE_SIZE: usize = SecretBox::<()>::KEY_SIZE;
I don't think this line is necessary, and is also incorrect (`NONCE` != `KEY`).

2023-07-29 23:30 UTC, FelixMcFelix commented on src/driver/tasks/mixer.rs
> +const TAG_SIZE: usize = SecretBox::<()>::TAG_SIZE;
Why not `use crate::driver::crypto::TAG_SIZE`?

2023-07-30 14:06 UTC, Sebbl0508 commented
I've adjusted the code. hope it looks good now

2023-07-31 09:12 UTC, FelixMcFelix approved these changes
Great, looks good to me! Thank you. :)

2023-07-31 09:50 UTC, merged