Switch IDs to use NonMax internally
serenity-rs/songbird pull request #218
Opened 2024-01-16 23:40 UTC by GnomedDev

Serenity has made this switch, as it allows the cool niche opts without causing collisions with buggy discord code leading to this.

2024-01-17 11:02 UTC, FelixMcFelix requested changes
I'm happy with the Id-focussed changes, and I think that serenity's new UserData functionality is a great improvement. Thanks for taking the time to port there.

The TrackHandle changes are a great idea in principle, but I think they need a little bit more iteration to work like they do today.

(Apologies for brevity/typos, reviewing from my phone under some time
constraints!)

2024-01-17 11:02 UTC, FelixMcFelix commented on src/tracks/handle.rs
> +    data: Arc<dyn std::any::Any + Send + Sync + 'static>,
I can see why you've done this, but moving this outside of InnerHandle to get an &mut won't work for reasons outlined below.

2024-01-17 11:02 UTC, FelixMcFelix commented on src/tracks/handle.rs
> +        Data: Send + Sync + 'static,
This won't set the data in any meaningful way. By the time a user can acquire a TrackHandle, it is a shared resource: one copy exists in the audio context, one copy in user code. A `set` here will not propagate the new data to any Handles returned alongside event handlers etc. The question is then how to get the chosen data into InnerHandle -- Arc::get_mut on a nested Arc won't work for the same reason.

I think it might be valid to put the `Arc<dyn Any>` into `Track` and source InnerHandle::data from there during handle creation? It can either be optioned or default to `Arc<() as _>`?This lets us continue avoiding locks like your new approach and keeps TrackHandle::clone bounded to a single Arc clone.

2024-01-17 11:05 UTC, GnomedDev commented on src/tracks/handle.rs
> +        Data: Send + Sync + 'static,
Ah, okay, I was somewhat unaware how this API was used. I'll have a look at moving it to Track.

2024-01-17 12:20 UTC, GnomedDev commented on src/tracks/handle.rs
> +        Data: Send + Sync + 'static,
Moved to #219.

2024-01-21 21:08 UTC, FelixMcFelix approved these changes
Great, thanks for splitting out the other changes.

2024-01-21 21:08 UTC, merged